### ISSUE TITLE
Hosting Request: Google Summer of Code Daily Logs

### ISSUE THREAD

**Issue by eysk-io** [keptn-sandbox/contributing#12]
### Feature Request

This new repository will contain all the logs and asynchronous scrum notes for my [Google Summer of Code 2022 project](https://summerofcode.withgoogle.com/programs/2022/projects/yd9z3DBo). This is in lieu of in-person daily scrum meetings.

### References

link to repo: https://github.com/eyskim/gsoc22-daily

cc @oleg-nenashev

**Comment by oleg-nenashev** [comment]
Why does it need a separate repository? It could be a part of your project repository, or maybe a Wiki page there

**Comment by mehabhalodiya** [comment]
@oleg-nenashev I don't think that we should keep GSoC info inside the main project repository because project repo might be having it's own stuff like guidelines, set up, how it works, and all. 

While in our GSoC repo, all things related to the daily updates, meetings notes, proposal, etc. can be there. Not sure if this requires hosting request!

**Comment by eysk-io** [comment]
> Why does it need a separate repository? It could be a part of your project repository, or maybe a Wiki page there

Thanks for the response! I think I may have been too hasty in requesting this. Definitely agree a Wiki page would be better for this.
